src/services/applicationChecks.js
src/services/fluxService.js

Fix FDM hangs.
The branch can be deleted after the merge.
axios timeout only acts to stablish a connection. added cancel token to cancel in cases where the connection is stablished but the data is not returned, keeps loading forever and axios stops working and the app stops.

Fix FDM hangs

---

src/services/domainService.js

demise old deployment ssl as well

chore: add kadefi money new chainweb node for ssl

---

src/routes.js
src/services/api/index.js
src/services/constants.js
src/services/domain/cert.js
src/services/domain/dns.js
src/services/domain/index.js
src/services/domainService.js

This PR splits the `domainService.js` into separate files.
Currently the `domainService.js` has multiple responsibilities.
1. DNS Management - Create/List/Delete DNS Records from Cloudflare/PDNS
2. Certificate Management - Managing Certificates for the DNS records from CF/PDNS
3. HAProxy Config Generation - Final generation of `haproxy.cfg` file for main app or flux applications
These 3 responsibilities are highly coupled with each other, however, it does not need to reside in one huge file.
This PR will split them into separate folders/modules, which will make things easier to refactor down the line. This is one of the first refactoring PRs to FDM.

refactor: move code to different files/structure

---

src/services/application/checks.js
src/services/application/custom.js
src/services/constants.js
src/services/domain/index.js
src/services/domainService.js
src/services/flux/index.js
src/services/haproxyTemplate.js

Making further refactoring for FDM, moving Flux Service to another module and removing unused code

refactor: move code around, reuse code

---

src/services/application/checks.js

Supported  blockbook: litecoin,flux,ethereumclassic,vertcoin,zcash,dogecoin,digibyte,groestlcoin,dash,firo,sinovate,ravencoin

added checkBlockBook

---

src/services/application/checks.js

- removed duplication in ethers checks

added etherscheck

---

src/services/application/custom.js

My application needs proxy for postgres which can only be done through TCP mode

use mode tcp for pgbouncer

---

src/services/application/checks.js
src/services/domainService.js

- Complete separate methods to process non g apps and g apps;
- Adds timeout/cancel token to checkAppRunning message call;
- Awaits if a new update of haproxy is needed and another one is currently happening;
- Other optimizations/simplifications.

Separate processing

---

src/services/application/custom.js

Update custom.js - Add SSL for Freindica

---

src/services/application/custom.js

changed to only wordpress1677413615318

Update custom.js - Specifc to Toms Wordpress Instance

---

src/services/application/custom.js

Update custom.js - Onlyoffice SSL

---

src/services/application/custom.js

Add ssl true for alephium explorer

Update custom.js - Add ssl true for alephium explorer

---

src/services/application/custom.js

Add AlephiumExplorer2 + TCP Mode

Update custom.js - Add AlephiumExplorer2 + TCP Mode

---

src/services/application/custom.js

ssl true for owncloudssl nginx container port 38888

Update custom.js - Add ssl to owncloud

---

src/services/application/custom.js

headers: ['http-response set-header X-Frame-Options SAMEORIGIN', 'http-response set-header X-XSS-Protection "0"', 'http-response set-header X-Content-Type-Options nosniff'],

Update custom.js - Add Custom Headers to Owncloudssl

---

src/services/application/checks.js

Add check for Ergo Blockchain Height using /info endpoint

Update checks.js - Add check for Ergo

---

src/services/application/checks.js

Updated ergo check to use maxPeerHeight and headersHeight 
Uses equal to - instead of greater than or equal to 
Removed the height parameter

Update checks.js - Update Ergo check

---

src/services/application/custom.js

Remove ssl flag for meshcentral 
Add ssl flag for; listmonk, formbricks, adguard, budibasemysql

Update custom.js - Update Custom Configs For Multiple Apps

---

src/services/application/custom.js

1. Add headers for ghostflux app
2. Add TCP mode for adguard
3. Add SSL flag for whooglessl instances

Update custom.js - Add For Multiple Apps

---

src/services/application/custom.js

Update custom.js - Assume HTTPS

---

src/services/haproxyTemplate.js

- Preserves state after HAproxy reload

Preserve state after HAproxy reload

---

src/services/haproxyTemplate.js

Adjust haproxy logging level
Load state file

adjust logging + load state file

---

src/services/haproxyTemplate.js

Fixes issue where nodes don't come up after master failover

Hotfix for backup nodes not coming up after master change
